server:
  port: 8802
spring:
  mail:
    #配置邮件服务器
    host: smtp.exmail.qq.com
    username: abc@qq.com
    password: 123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#邮件通知
  boot:
    admin:
      notify:
        mail:
          # 是谁发送出去的
          from: abc@qq.com
          # 发送给谁
          to: abc@126.com
#钉钉通知
  boot:
    admin:
      notify:
        dingtalk:
          enabled: false
          webhook-token: https://oapi.dingtalk.com/robot/send?access_token=****
          atMobiles:
            #- 12345678901