spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8&useSSL=false
            username: root
            password: 123456
            #初始化时建立物理连接的个数
            initial-size: 10
            #最小连接池数量
            min-idle: 10
            #最大连接池数量 maxIdle已经不再使用
            max-active: 100
            #获取连接时最大等待时间，单位毫秒
            max-wait: 60000
            #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
            test-while-idle: true
            #既作为检测的间隔时间又作为testWhileIdel执行的依据
            time-between-eviction-runs-millis: 60000
            #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
            min-evictable-idle-time-millis: 30000
            #用来检测连接是否有效的sql 必须是一个查询语句
            #mysql,sqlServer中为 select 'x'
            #oracle中为 select 1 from dual
            validation-query: select 'x'
            #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
            test-on-borrow: false
            #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
            test-on-return: false
            #当数据库抛出不可恢复的异常时,抛弃该连接
            #exception-sorter: true
            #是否缓存preparedStatement,mysql5.5+建议开启
            #spring.datasource.druid.pool-prepared-statements=true
            #当值大于0时poolPreparedStatements会自动修改为true
            max-pool-prepared-statement-per-connection-size: 20
            #配置扩展插件
            filters: stat,wall
            #通过connectProperties属性来打开mergeSql功能；慢SQL记录
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
            #合并多个DruidDataSource的监控数据
            #use-global-data-source-stat: true
            #设置访问druid监控页的账号和密码,默认没有
            #stat-view-servlet:
            #  login-username: admin
            #  login-password: admin
    redis:
        database: 0
        host: localhost
        port: 6379
        password:       # 密码（默认为空）
        timeout: 6000ms  # 连接超时时长（毫秒）
        jedis:
          pool:
              max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
              max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
              max-idle: 10      # 连接池中的最大空闲连接
              min-idle: 5       # 连接池中的最小空闲连接
