spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
#        driverClassName: oracle.jdbc.OracleDriver
#        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        druid:
            url: jdbc:mysql://localhost:3306/gen?useUnicode=true&characterEncoding=UTF-8&useSSL=false
            username: root
            password: 123456

#            url: jdbc:sqlserver://zjf-sqlserver-dev:1433;DatabaseName=gen
#            username: DBuser
#            password: qwer#@!

#            url: jdbc:oracle:thin:@192.168.0.183:1521:gen
#            username: root
#            password: 1234567
            initial-size: 10
            min-idle: 10
            max-active: 100
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 30000
            # sqlServer
            validation-query: select 'x'
#            oracle mysql
#            validation-query: select 'x' FROM DUAL
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            max-pool-prepared-statement-per-connection-size: 20
            filters: stat,wall
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
            #use-global-data-source-stat: true
            #stat-view-servlet:
            #  login-username: admin
            #  login-password: admin
    redis:
        host: zjf-redis-dev
        port: 6379
        password:       # 密码（默认为空）
        timeout: 6000ms  # 连接超时时长（毫秒）
        lettuce:
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接
logging:
  level-log: debug